In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
banking=pd.read_csv('featured_bank.csv')

In [3]:
banking.head()

s.no  age        job  marital    education  default housing loan  \
0     1   56  housemaid  married     basic.4y       no      no   no   
1     2   57   services  married  high.school  unknown      no   no   
2     3   37   services  married  high.school       no     yes   no   
3     4   40     admin.  married     basic.6y       no      no   no   
4     5   56   services  married  high.school       no      no  yes   

     contact month  ... emp.var.rate  cons.price.idx  cons.conf.idx  \
0  telephone   may  ...          1.1          93.994          -36.4   
1  telephone   may  ...          1.1          93.994          -36.4   
2  telephone   may  ...          1.1          93.994          -36.4   
3  telephone   may  ...          1.1          93.994          -36.4   
4  telephone   may  ...          1.1          93.994          -36.4   

   euribor3m  nr.employed   y  f.euribor     f.age  f.duration  f.pattern  
0      4.857         5191  no         >4  51_to_60  201_to_300         no  
1      4.857         5191  no         >4  51_to_60  101_to_200         no  
2      4.857         5191  no         >4  31_to_40  201_to_300         no  
3      4.857         5191  no         >4  31_to_40  101_to_200         no  
4      4.857         5191  no         >4  51_to_60  301_to_400         no  

[5 rows x 26 columns]

In [4]:
banking.shape

(41188, 26)

In [70]:
banking['y'].value_counts()

no     36548
yes     4640
Name: y, dtype: int64

In [6]:
banking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   s.no            41188 non-null  int64  
 1   age             41188 non-null  int64  
 2   job             41188 non-null  object 
 3   marital         41188 non-null  object 
 4   education       41188 non-null  object 
 5   default         41188 non-null  object 
 6   housing         41188 non-null  object 
 7   loan            41188 non-null  object 
 8   contact         41188 non-null  object 
 9   month           41188 non-null  object 
 10  day_of_week     41188 non-null  object 
 11  duration        41188 non-null  int64  
 12  campaign        41188 non-null  int64  
 13  pdays           41188 non-null  int64  
 14  previous        41188 non-null  int64  
 15  poutcome        41188 non-null  object 
 16  emp.var.rate    41188 non-null  float64
 17  cons.price.idx  41188 non-null 

# Encoding

In [7]:
banking_encoded=pd.get_dummies(banking[['job','marital','education','default','housing','loan','contact','month','day_of_week','poutcome','f.euribor','f.age','f.duration','f.pattern']])

In [8]:
banking_df=pd.concat([banking_encoded,banking[['campaign','previous','emp.var.rate','cons.price.idx','cons.conf.idx',
                                                       'nr.employed','y']]],axis=1)

In [45]:
banking_df_rem=pd.concat([banking_encoded,banking[['campaign','previous','cons.price.idx',
                                                      'y']]],axis=1)

In [9]:
banking_df.head()

job_admin.  job_blue-collar  job_entrepreneur  job_housemaid  \
0           0                0                 0              1   
1           0                0                 0              0   
2           0                0                 0              0   
3           1                0                 0              0   
4           0                0                 0              0   

   job_management  job_retired  job_self-employed  job_services  job_student  \
0               0            0                  0             0            0   
1               0            0                  0             1            0   
2               0            0                  0             1            0   
3               0            0                  0             0            0   
4               0            0                  0             1            0   

   job_technician  ...  f.pattern_PE4F  f.pattern_PE4G  f.pattern_no  \
0               0  ...               0               0             1   
1               0  ...               0               0             1   
2               0  ...               0               0             1   
3               0  ...               0               0             1   
4               0  ...               0               0             1   

   campaign  previous  emp.var.rate  cons.price.idx  cons.conf.idx  \
0         1         0           1.1          93.994          -36.4   
1         1         0           1.1          93.994          -36.4   
2         1         0           1.1          93.994          -36.4   
3         1         0           1.1          93.994          -36.4   
4         1         0           1.1          93.994          -36.4   

   nr.employed   y  
0         5191  no  
1         5191  no  
2         5191  no  
3         5191  no  
4         5191  no  

[5 rows x 124 columns]

# Logistic Model for the Featured Data Set

In [10]:
X=banking_df.drop(columns=['y'])

In [12]:
y=banking_df['y']

In [13]:
 X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=101)

In [14]:
X_train.head()

job_admin.  job_blue-collar  job_entrepreneur  job_housemaid  \
18897           0                0                 0              0   
25546           1                0                 0              0   
16054           0                1                 0              0   
8799            0                0                 0              1   
28557           0                0                 0              0   

       job_management  job_retired  job_self-employed  job_services  \
18897               0            0                  0             0   
25546               0            0                  0             0   
16054               0            0                  0             0   
8799                0            0                  0             0   
28557               0            1                  0             0   

       job_student  job_technician  ...  f.pattern_PE4E  f.pattern_PE4F  \
18897            0               1  ...               0               0   
25546            0               0  ...               0               0   
16054            0               0  ...               0               0   
8799             0               0  ...               0               0   
28557            0               0  ...               0               0   

       f.pattern_PE4G  f.pattern_no  campaign  previous  emp.var.rate  \
18897               0             1         1         0           1.4   
25546               0             1         1         1          -0.1   
16054               0             1         1         0           1.4   
8799                0             1         1         0           1.4   
28557               0             1         1         0          -1.8   

       cons.price.idx  cons.conf.idx  nr.employed  
18897          93.444          -36.1         5228  
25546          93.200          -42.0         5196  
16054          93.918          -42.7         5228  
8799           94.465          -41.8         5228  
28557          93.075          -47.1         5099  

[5 rows x 123 columns]

In [15]:
X_train.shape

(30891, 123)

In [68]:
y_train.value_counts()

no     27416
yes     3475
Name: y, dtype: int64

In [69]:
y_test.value_counts()

no     9132
yes    1165
Name: y, dtype: int64

In [16]:
lrf=LogisticRegression()

In [17]:
lrf.fit(X_train,y_train)

C:\Users\srika\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [18]:
predictions_LRF=lrf.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [21]:
print('accuracy:\n',accuracy_score(y_test,predictions_LRF))
print('classification_report:\n',classification_report(y_test,predictions_LRF))
print('confusion_matrix:\n',confusion_matrix(y_test,predictions_LRF))

accuracy:
 0.8966689326988443
classification_report:
               precision    recall  f1-score   support

          no       0.91      0.98      0.94      9132
         yes       0.60      0.26      0.36      1165

    accuracy                           0.90     10297
   macro avg       0.76      0.62      0.65     10297
weighted avg       0.88      0.90      0.88     10297

confusion_matrix:
 [[8932  200]
 [ 864  301]]


# Decision Tree for Featured Model Data Set

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
dtf=DecisionTreeClassifier()

In [33]:
dtf.fit(X_train,y_train)

DecisionTreeClassifier()

In [35]:
predictions_dtf=dtf.predict(X_test)

In [36]:
print('accuracy:\n',accuracy_score(y_test,predictions_dtf))
print('classification_report:\n',classification_report(y_test,predictions_dtf))
print('confusion_matrix:\n',confusion_matrix(y_test,predictions_dtf))

accuracy:
 0.8863746722346314
classification_report:
               precision    recall  f1-score   support

          no       0.94      0.94      0.94      9132
         yes       0.50      0.49      0.50      1165

    accuracy                           0.89     10297
   macro avg       0.72      0.71      0.72     10297
weighted avg       0.89      0.89      0.89     10297

confusion_matrix:
 [[8553  579]
 [ 591  574]]


# Random Forest for Featured Model Data Set

In [37]:
from sklearn.ensemble import RandomForestClassifier

In [38]:
rff=RandomForestClassifier()

In [39]:
rff.fit(X_train,y_train)

RandomForestClassifier()

In [42]:
predictions_rff=rff.predict(X_test)

In [43]:
print('accuracy:\n',accuracy_score(y_test,predictions_rff))
print('classification_report:\n',classification_report(y_test,predictions_rff))
print('confusion_matrix:\n',confusion_matrix(y_test,predictions_rff))

accuracy:
 0.9074487714868408
classification_report:
               precision    recall  f1-score   support

          no       0.93      0.97      0.95      9132
         yes       0.64      0.43      0.51      1165

    accuracy                           0.91     10297
   macro avg       0.78      0.70      0.73     10297
weighted avg       0.90      0.91      0.90     10297

confusion_matrix:
 [[8847  285]
 [ 668  497]]


# Models with few columns removed 

In [50]:
X_rem=banking_df_rem.drop(columns=['y'])

In [51]:
y_rem=banking_df_rem['y']

In [52]:
 X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_rem, y_rem, test_size=0.25, random_state=101)

In [53]:
lrr=LogisticRegression()

In [54]:
lrr.fit( X_train_r,y_train_r)

C:\Users\srika\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [55]:
predictions_lrr=lrr.predict(X_test_r)


In [57]:
print('accuracy:\n',accuracy_score(y_test,predictions_lrr))
print('classification_report:\n',classification_report(y_test,predictions_lrr))
print('confusion_matrix:\n',confusion_matrix(y_test,predictions_lrr))

accuracy:
 0.9072545401573274
classification_report:
               precision    recall  f1-score   support

          no       0.93      0.97      0.95      9132
         yes       0.65      0.38      0.48      1165

    accuracy                           0.91     10297
   macro avg       0.79      0.68      0.72     10297
weighted avg       0.89      0.91      0.90     10297

confusion_matrix:
 [[8895  237]
 [ 718  447]]


In [58]:
dtr=DecisionTreeClassifier()

In [59]:
dtr.fit( X_train_r,y_train_r)

DecisionTreeClassifier()

In [61]:
predictions_dtr=dtr.predict(X_test_r)

In [62]:
print('accuracy:\n',accuracy_score(y_test,predictions_dtr))
print('classification_report:\n',classification_report(y_test,predictions_dtr))
print('confusion_matrix:\n',confusion_matrix(y_test,predictions_dtr))

accuracy:
 0.8899679518306303
classification_report:
               precision    recall  f1-score   support

          no       0.94      0.94      0.94      9132
         yes       0.51      0.53      0.52      1165

    accuracy                           0.89     10297
   macro avg       0.73      0.73      0.73     10297
weighted avg       0.89      0.89      0.89     10297

confusion_matrix:
 [[8550  582]
 [ 551  614]]


In [63]:
rfr=RandomForestClassifier()

In [64]:
rfr.fit( X_train_r,y_train_r)

RandomForestClassifier()

In [65]:
predictions_rfr=rfr.predict(X_test_r)

In [66]:
print('accuracy:\n',accuracy_score(y_test,predictions_rfr))
print('classification_report:\n',classification_report(y_test,predictions_rfr))
print('confusion_matrix:\n',confusion_matrix(y_test,predictions_rfr))

accuracy:
 0.9074487714868408
classification_report:
               precision    recall  f1-score   support

          no       0.93      0.97      0.95      9132
         yes       0.65      0.40      0.50      1165

    accuracy                           0.91     10297
   macro avg       0.79      0.69      0.72     10297
weighted avg       0.90      0.91      0.90     10297

confusion_matrix:
 [[8875  257]
 [ 696  469]]


In [71]:
from sklearn.model_selection import GridSearchCV

In [72]:
params= {'n_estimators':[200,500,700],'max_depth':[10,15,18,20],
        'min_samples_leaf':[3,5,7]}

In [73]:
gs=GridSearchCV(rfr,params,verbose=3)

In [74]:
gs.fit(X_train_r,y_train_r)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.903, total=   7.0s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.9s remaining:    0.0s


[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.902, total=   6.4s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   13.3s remaining:    0.0s


[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.913, total=   6.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.903, total=   6.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.906, total=   6.5s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.903, total=  15.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.902, total=  15.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.913, total=  15.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=

[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.908, total=  32.2s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.908, total=  34.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.916, total=  35.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.909, total=  32.6s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.912, total=  33.2s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=0.907, total=   8.8s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=

[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.907, total=   9.1s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.912, total=  10.0s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.907, total=  24.8s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.908, total=  23.2s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.918, total=  17.3s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.908, total=  16.6s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=

[CV]  max_depth=20, min_samples_leaf=5, n_estimators=700, score=0.909, total=  25.0s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=700, score=0.919, total=  29.0s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=700, score=0.909, total=  29.0s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=700, score=0.913, total=  25.9s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=200, score=0.907, total=   7.1s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=200, score=0.907, total=   7.4s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=200, score=

[Parallel(n_jobs=1)]: Done 180 out of 180 | elapsed: 57.5min finished


GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'max_depth': [10, 15, 18, 20],
                         'min_samples_leaf': [3, 5, 7],
                         'n_estimators': [200, 500, 700]},
             verbose=3)

In [75]:
gs.best_params_

{'max_depth': 20, 'min_samples_leaf': 3, 'n_estimators': 700}

In [77]:
gs.best_estimator_

RandomForestClassifier(max_depth=20, min_samples_leaf=3, n_estimators=700)

In [78]:
rfGS=RandomForestClassifier(max_depth=20, min_samples_leaf=3, n_estimators=700)

In [79]:
rfGS.fit(X_train_r,y_train_r)

RandomForestClassifier(max_depth=20, min_samples_leaf=3, n_estimators=700)

In [80]:
predictions_rfGS=rfGS.predict(X_test_r)

In [81]:
print('accuracy:\n',accuracy_score(y_test,predictions_rfGS))
print('classification_report:\n',classification_report(y_test,predictions_rfGS))
print('confusion_matrix:\n',confusion_matrix(y_test,predictions_rfGS))

accuracy:
 0.9063804991745168
classification_report:
               precision    recall  f1-score   support

          no       0.92      0.98      0.95      9132
         yes       0.70      0.30      0.42      1165

    accuracy                           0.91     10297
   macro avg       0.81      0.64      0.68     10297
weighted avg       0.89      0.91      0.89     10297

confusion_matrix:
 [[8985  147]
 [ 817  348]]


In [82]:
rfGS.feature_importances_

array([6.50856204e-03, 5.83700010e-03, 8.99403345e-04, 7.53747804e-04,
       2.67999755e-03, 5.41769561e-03, 1.30631596e-03, 2.90194106e-03,
       3.95333735e-03, 5.23998354e-03, 1.32224696e-03, 3.72613189e-04,
       3.42550121e-03, 6.65039470e-03, 6.28978200e-03, 1.41606828e-04,
       3.33936652e-03, 1.49852634e-03, 4.07330210e-03, 5.73222913e-03,
       1.49086144e-05, 4.09567567e-03, 8.00531980e-03, 2.11021871e-03,
       5.01026913e-03, 4.38442789e-03, 0.00000000e+00, 6.85471647e-03,
       6.47014736e-04, 6.72595363e-03, 4.67291255e-03, 6.52965057e-04,
       4.18342781e-03, 1.07812340e-02, 1.03466374e-02, 7.91349008e-03,
       4.32939130e-03, 1.22856446e-03, 4.07180092e-03, 1.06145706e-02,
       1.08284928e-02, 1.76846691e-02, 3.80872480e-03, 1.22876794e-02,
       4.60685502e-03, 6.24947919e-03, 6.95223122e-03, 6.52723484e-03,
       5.86083836e-03, 5.81633853e-03, 1.39211053e-02, 1.49596668e-02,
       7.14054476e-02, 9.01446997e-02, 1.85968285e-02, 1.46281400e-05,
      

In [83]:
sorted(list(zip(rfGS.feature_importances_,banking_df_rem.columns)),reverse= True)

[(0.09014469972698069, 'f.euribor_<1'),
 (0.0714054475792952, 'poutcome_success'),
 (0.06785138576348412, 'cons.price.idx'),
 (0.054816828131862526, 'f.duration_0_to_100'),
 (0.05269337944783982, 'f.euribor_>4'),
 (0.051610294035377154, 'f.pattern_no'),
 (0.035717165762271914, 'f.duration_101_to_200'),
 (0.027804548418342165, 'f.duration_701_to_800'),
 (0.025129360793355482, 'f.duration_801_to_900'),
 (0.023310868167413453, 'f.duration_901_to_1000'),
 (0.023281802919687046, 'previous'),
 (0.021999781777536746, 'f.duration_601_to_700'),
 (0.018596828488999427, 'f.euribor_>1 and <2'),
 (0.01785623614802513, 'campaign'),
 (0.01768466905909969, 'month_may'),
 (0.01545018860353162, 'f.duration_201_to_300'),
 (0.014959666762355708, 'poutcome_nonexistent'),
 (0.013921105277387593, 'poutcome_failure'),
 (0.013865523772544833, 'f.duration_501_to_600'),
 (0.013677533330248673, 'f.duration_1001_to_1100'),
 (0.012287679424296304, 'month_oct'),
 (0.011046452274267027, 'f.duration_1301_to_1400'),
 (